name: run-experiment

on:
  push:
    branches:
      - run-experiment

jobs:
  run-experiment:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Run clean
      run: make clean

    - name: Pull data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    - name: Run experiment
      run: make 4090

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv_metrics
        path: cv_metrics_*.json
