name: run-experiment

on:
  push:
    branches:
      - run-experiment

jobs:
  run-experiment:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Run clean
      run: make clean

    - uses: iterative/setup-dvc@v1

    # https://github.com/iterative/dvc/pull/7213/
    - name: Pull data
      run: |
          dvc remote modify gdrive --local gdrive_use_service_account true
          dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install python dependencies
      run: pip install -U -r requirements.txt

    - name: Run experiment
      run: make 4090

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv_metrics
        path: cv_metrics_*.json
