name: run-experiment

on:
  push:
    branches:
      - run-experiment

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run clean
      run: make clean

    - name: dvc pull
      run: dvc pull

    - name: Run experiment
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv_metrics
        path: cv_metrics_*.json
