name: run-experiment

on:
  push:
    branches:
      - run-experiment
  workflow_dispatch:

jobs:
  run-experiment:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Run clean
      run: make clean

    - uses: iterative/setup-dvc@v1

    # https://github.com/iterative/dvc/pull/7213/
    - name: Pull data
      run: |
        dvc remote modify gdrive --local gdrive_use_service_account true
        dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install python dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install -r requirements.txt

    - name: Run experiment
      run: make 4090

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          logs_*.json
          logs_*.csv
